# Documentación API

# Group Login

## Login [/login]

+ Body

        {
            "email": "usuario@email.com",
            "pasword": "123456789"
        }

+ Attributes (object)
    + ok: true (boolean)
    + message: "Mensaje" (string)
    + token: "token" (string)

### Iniciar sesión [POST]

+ Request 

    + Headers

            Accept: application/json

+ Response 200 (application/json;charset=UTF-8)

    + Attributes(Login)

+ Response 401 (application/json;charset=UTF-8)

        {
            "ok": false,
            "message": "Mensaje con la descripción del error"
        }

# Group Usuario

## Usuario [/me]

+ Attributes (object)
    + id: "" (string)
    + email: "usuario@email.com" (string)
    + name: "Usuario" (string)
    + active: true (boolean)

### Obtener la información del usuario [GET]

+ Request 

    + Headers

            Accept: application/json
            Authorization: Bearer < Aquí se manda el token, sin los <> >

+ Response 200 (application/json;charset=UTF-8)

    + Attributes(Usuario)

+ Response 401 (application/json;charset=UTF-8)

        {
            "ok": false,
            "message": "Mensaje informando si el token no es correcto o ya ha caducado"
        }

+ Response 404 (application/json;charset=UTF-8)

        {
            "ok": false,
            "message": "Mensaje con la descripción del error"
        }

# Group Links

## Links [/get-links]

+ Body

        {
            "url": "https://google.com"
        }

### Obtener XLSX con enlaces [POST]

+ Request 

    + Headers

            Accept: application/json
            Authorization: Bearer < Aquí se manda el token, sin los <> >

+ Response 200 (application/vnd.ms-excel)

+ Response 401 (application/json;charset=UTF-8)

        {
            "ok": false,
            "message": "Mensaje informando si el token no es correcto o ya ha caducado"
        }

+ Response 404 (application/json;charset=UTF-8)

        {
            "ok": false,
            "message": "Mensaje con la descripción del error"
        }
